- name: Create the EC2 instance
  hosts: localhost
  gather_facts: false
  vars:
    name: myinstance
    ami: ami-09d56f8956ab235b3
    #Other vars ommited for brevity
  tasks:
    - name: Launch Instance
      ec2:
        key_name: ram
        group: public-web	
        instance_type: t2.micro
        image: "{{ ami }}"
        wait: true
        region: us-east-1
        vpc_subnet_id: subnet-0bec48aa43bb52e18
        assign_public_ip: yes
        exact_count: 1
        count_tag:
            Name: "{{ name }}"
        instance_tags:
          Name: from_ansible
      register: ec2